#!/bin/sh

file=$1

# Homopolymer length: 3+
awk '{if($2 != 4) {for(i=12; i <= NF; i++) {split($i,field,":"); if(field[1]=="MD") {str=field[3];pos=0;num=0;ind=0; for(it=1;it<=length(str);it++) {sb=substr(str,it,1); if(sb ~ /[0-9]/) {num=10*num+sb;} else if(sb == "^") {pos=pos+num;num=0;it++;while(substr(str,it,1) ~ /[AGCT]/) it++; it--;} else {pos=pos+num+1;num=0; new=sb; iter=0;pos2=0;num2=0;itt=0; while(itt<=length($6)) {itt++; bp=substr($6,itt,1); if(bp ~ /[0-9]/) {num2=10*num2+bp;} else if(bp=="D") {num2=0;} else if(bp ~ /[IS]/) {pos2=pos2+num2;num2=0;} else {iter=iter+num2;pos2=pos2+num2;num2=0;if(iter>=pos) {old=substr($10,pos2-iter+pos,1); ind++;arr[ind]=pos2-iter+pos;break; }}}}}}} if(ind>0){prev_index=0;next_index=10000; for(indit=1;indit<=ind;indit++){posit=arr[indit]-1; while(posit>2&&posit>prev_index){if(substr($10,posit,1)==substr($10,posit-1,1)&&substr($10,posit-1,1)==substr($10,posit-2,1)) {print arr[indit]-posit;break;} else {posit--;}} prev_index=arr[indit];if(indit<ind){next_index=arr[indit+1];}else{next_index=10000;} posit=arr[indit]+1; while(posit<length($10)-1&&posit<next_index-2) {if(substr($10,posit,1)==substr($10,posit+1,1)&&substr($10,posit+1,1)==substr($10,posit+2,1)){print posit-arr[indit];break;}else{posit++;}}}}}}' $file > homopolymer3.txt

# Homopolymer length: 4+
awk '{if($2 != 4) {for(i=12; i <= NF; i++) {split($i,field,":"); if(field[1]=="MD") {str=field[3];pos=0;num=0;ind=0; for(it=1;it<=length(str);it++) {sb=substr(str,it,1); if(sb ~ /[0-9]/) {num=10*num+sb;} else if(sb == "^") {pos=pos+num;num=0;it++;while(substr(str,it,1) ~ /[AGCT]/) it++; it--;} else {pos=pos+num+1;num=0; new=sb; iter=0;pos2=0;num2=0;itt=0; while(itt<=length($6)) {itt++; bp=substr($6,itt,1); if(bp ~ /[0-9]/) {num2=10*num2+bp;} else if(bp=="D") {num2=0;} else if(bp ~ /[IS]/) {pos2=pos2+num2;num2=0;} else {iter=iter+num2;pos2=pos2+num2;num2=0;if(iter>=pos) {old=substr($10,pos2-iter+pos,1); ind++;arr[ind]=pos2-iter+pos;break; }}}}}}} if(ind>0){prev_index=0;next_index=10000; for(indit=1;indit<=ind;indit++){posit=arr[indit]-1; while(posit>3&&posit>prev_index){if(substr($10,posit,1)==substr($10,posit-1,1)&&substr($10,posit-1,1)==substr($10,posit-2,1)&&substr($10,posit-2,1)==substr($10,posit-3,1)) {print arr[indit]-posit;break;} else {posit--;}} prev_index=arr[indit];if(indit<ind){next_index=arr[indit+1];}else{next_index=10000;} posit=arr[indit]+1; while(posit<length($10)-2&&posit<next_index-3) {if(substr($10,posit,1)==substr($10,posit+1,1)&&substr($10,posit+1,1)==substr($10,posit+2,1)&&substr($10,posit+2,1)==substr($10,posit+3,1)){print posit-arr[indit];break;}else{posit++;}}}}}}' $file > homopolymer4.txt

# Homopolymer length: 5+
awk '{if($2 != 4) {for(i=12; i <= NF; i++) {split($i,field,":"); if(field[1]=="MD") {str=field[3];pos=0;num=0;ind=0; for(it=1;it<=length(str);it++) {sb=substr(str,it,1); if(sb ~ /[0-9]/) {num=10*num+sb;} else if(sb == "^") {pos=pos+num;num=0;it++;while(substr(str,it,1) ~ /[AGCT]/) it++; it--;} else {pos=pos+num+1;num=0; new=sb; iter=0;pos2=0;num2=0;itt=0; while(itt<=length($6)) {itt++; bp=substr($6,itt,1); if(bp ~ /[0-9]/) {num2=10*num2+bp;} else if(bp=="D") {num2=0;} else if(bp ~ /[IS]/) {pos2=pos2+num2;num2=0;} else {iter=iter+num2;pos2=pos2+num2;num2=0;if(iter>=pos) {old=substr($10,pos2-iter+pos,1); ind++;arr[ind]=pos2-iter+pos;break; }}}}}}} if(ind>0){prev_index=0;next_index=10000; for(indit=1;indit<=ind;indit++){posit=arr[indit]-1; while(posit>4&&posit>prev_index){if(substr($10,posit,1)==substr($10,posit-1,1)&&substr($10,posit-1,1)==substr($10,posit-2,1)&&substr($10,posit-2,1)==substr($10,posit-3,1)&&substr($10,posit-3,1)==substr($10,posit-4,1)) {print arr[indit]-posit;break;} else {posit--;}} prev_index=arr[indit];if(indit<ind){next_index=arr[indit+1];}else{next_index=10000;} posit=arr[indit]+1; while(posit<length($10)-3&&posit<next_index-4) {if(substr($10,posit,1)==substr($10,posit+1,1)&&substr($10,posit+1,1)==substr($10,posit+2,1)&&substr($10,posit+2,1)==substr($10,posit+3,1)&&substr($10,posit+3,1)==substr($10,posit+4,1)){print posit-arr[indit];break;}else{posit++;}}}}}}' $file > homopolymer5.txt

cat homopolymer3.txt | sort -n | uniq -c | awk '{sub(/^[ \t]+/, "");print $2, "\t", $1}' > ploth3.txt
cat homopolymer4.txt | sort -n | uniq -c | awk '{sub(/^[ \t]+/, "");print $2, "\t", $1}' > ploth4.txt
cat homopolymer5.txt | sort -n | uniq -c | awk '{sub(/^[ \t]+/, "");print $2, "\t", $1}' > ploth5.txt

nreads=`awk 'BEGIN{sum=0;} {if($2!=4) sum=sum+1;} END{print sum;}' $file` 

cat homopolymer3.txt | sort -n | uniq -c | head -3 | awk -v reads=$nreads '{sub(/^[ \t]+/, "");print $2, "\t", $1/reads}' > plotrh3.txt
cat homopolymer4.txt | sort -n | uniq -c | head -3 | awk -v reads=$nreads '{sub(/^[ \t]+/, "");print $2, "\t", $1/reads}' > plotrh4.txt
cat homopolymer5.txt | sort -n | uniq -c | head -3 | awk -v reads=$nreads '{sub(/^[ \t]+/, "");print $2, "\t", $1/reads}' > plotrh5.txt

